<?php

/**
 * Implements hook_theme().
 */
function language_selection_page_theme($existing, $type, $theme, $path) {
  return [
    'language_selection_page' => [
      'render element' => 'custom_page',
      'path' => $path . '/templates',
      'template' => 'language-selection-page',
      'variables' => [
        'content' => NULL,
      ],
    ],
    'language_selection_page_content' => [
      'render element' => 'custom_page',
      'path' => $path . '/templates',
      'template' => 'language-selection-page-content',
      'variables' => [
        'destination' => NULL,
        'configure_url' => \Drupal\Core\Url::fromRoute('language.negotiation'),
        'language_links' => ''
      ],
    ],
  ];
}